version: '3'
services:
  country-info:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: country-info
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    networks:
      - datalayer_country_network
      - api_network

networks:
  datalayer_country_network:
    external:
      name: datalayer_country_network
  api_network:
    driver: bridge